### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by sadman-ichha** [Ashish-Raturi/scroll_loop_auto_scroll#9]
E/flutter ( 5030): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 157 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter ( 5030): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
E/flutter ( 5030): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 5030): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:157:12)
E/flutter ( 5030): #3      _ScrollLoopAutoScrollState.animationHandler (package:scroll_loop_auto_scroll/scroll_loop_auto_scroll.dart:124:26)
E/flutter ( 5030): #4      _ScrollLoopAutoScrollState.initState.<anonymous closure> (package:scroll_loop_auto_scroll/scroll_loop_auto_scroll.dart:117:7)
E/flutter ( 5030): <asynchronous suspension>

**Comment by matteoberla** [comment]
same error here
